# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  dev:
    watch: true
    cmds:
      # https://qiita.com/growsic/items/492518f472c29ccde3db
      # https://ymtdzzz.dev/post/using-ga-task-to-host-reload/
      - cmd: kill $(lsof -t -i:3000)
        ignore_error: true
      - cd web && pnpm build 
      - go run . serve
    sources:
      - ./web/src/**/*
