// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {usecase} from '../models';

export function Chat(arg1:usecase.ChatRequest):Promise<usecase.ChatResponse>;

export function CreateBinder(arg1:usecase.CreateBinderRequest):Promise<usecase.ServeCreateResponse>;

export function CreateNote(arg1:usecase.CreateNoteRequest):Promise<usecase.ServeCreateResponse>;

export function DeleteBinder(arg1:number):Promise<void>;

export function ListActios():Promise<Array<usecase.ListActionsItem>>;

export function ListBinders():Promise<Array<usecase.ListBindersItem>>;

export function ListNotes(arg1:number):Promise<Array<usecase.ListNotesItem>>;
