// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function CreateBinder(arg1) {
  return window['go']['main']['App']['CreateBinder'](arg1);
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function DeleteBinder(arg1) {
  return window['go']['main']['App']['DeleteBinder'](arg1);
}

export function ListActios() {
  return window['go']['main']['App']['ListActios']();
}

export function ListBinders() {
  return window['go']['main']['App']['ListBinders']();
}

export function ListNotes(arg1) {
  return window['go']['main']['App']['ListNotes'](arg1);
}
