// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function Greet2(arg1:string):Promise<string>;

export function ListBinders():Promise<Array<service.Binder>>;
