// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/enuesaa/pinit/internal/ent/binder"
)

// BinderCreate is the builder for creating a Binder entity.
type BinderCreate struct {
	config
	mutation *BinderMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (bc *BinderCreate) SetName(s string) *BinderCreate {
	bc.mutation.SetName(s)
	return bc
}

// SetCategory sets the "category" field.
func (bc *BinderCreate) SetCategory(s string) *BinderCreate {
	bc.mutation.SetCategory(s)
	return bc
}

// SetArchivedAt sets the "archived_at" field.
func (bc *BinderCreate) SetArchivedAt(t time.Time) *BinderCreate {
	bc.mutation.SetArchivedAt(t)
	return bc
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (bc *BinderCreate) SetNillableArchivedAt(t *time.Time) *BinderCreate {
	if t != nil {
		bc.SetArchivedAt(*t)
	}
	return bc
}

// SetCreatedAt sets the "created_at" field.
func (bc *BinderCreate) SetCreatedAt(t time.Time) *BinderCreate {
	bc.mutation.SetCreatedAt(t)
	return bc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bc *BinderCreate) SetNillableCreatedAt(t *time.Time) *BinderCreate {
	if t != nil {
		bc.SetCreatedAt(*t)
	}
	return bc
}

// SetUpdatedAt sets the "updated_at" field.
func (bc *BinderCreate) SetUpdatedAt(t time.Time) *BinderCreate {
	bc.mutation.SetUpdatedAt(t)
	return bc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (bc *BinderCreate) SetNillableUpdatedAt(t *time.Time) *BinderCreate {
	if t != nil {
		bc.SetUpdatedAt(*t)
	}
	return bc
}

// SetID sets the "id" field.
func (bc *BinderCreate) SetID(u uint) *BinderCreate {
	bc.mutation.SetID(u)
	return bc
}

// Mutation returns the BinderMutation object of the builder.
func (bc *BinderCreate) Mutation() *BinderMutation {
	return bc.mutation
}

// Save creates the Binder in the database.
func (bc *BinderCreate) Save(ctx context.Context) (*Binder, error) {
	bc.defaults()
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BinderCreate) SaveX(ctx context.Context) *Binder {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BinderCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BinderCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BinderCreate) defaults() {
	if _, ok := bc.mutation.CreatedAt(); !ok {
		v := binder.DefaultCreatedAt()
		bc.mutation.SetCreatedAt(v)
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		v := binder.DefaultUpdatedAt()
		bc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BinderCreate) check() error {
	if _, ok := bc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Binder.name"`)}
	}
	if v, ok := bc.mutation.Name(); ok {
		if err := binder.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Binder.name": %w`, err)}
		}
	}
	if _, ok := bc.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Binder.category"`)}
	}
	if v, ok := bc.mutation.Category(); ok {
		if err := binder.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Binder.category": %w`, err)}
		}
	}
	if _, ok := bc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Binder.created_at"`)}
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Binder.updated_at"`)}
	}
	return nil
}

func (bc *BinderCreate) sqlSave(ctx context.Context) (*Binder, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BinderCreate) createSpec() (*Binder, *sqlgraph.CreateSpec) {
	var (
		_node = &Binder{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(binder.Table, sqlgraph.NewFieldSpec(binder.FieldID, field.TypeUint))
	)
	if id, ok := bc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := bc.mutation.Name(); ok {
		_spec.SetField(binder.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := bc.mutation.Category(); ok {
		_spec.SetField(binder.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := bc.mutation.ArchivedAt(); ok {
		_spec.SetField(binder.FieldArchivedAt, field.TypeTime, value)
		_node.ArchivedAt = &value
	}
	if value, ok := bc.mutation.CreatedAt(); ok {
		_spec.SetField(binder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := bc.mutation.UpdatedAt(); ok {
		_spec.SetField(binder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// BinderCreateBulk is the builder for creating many Binder entities in bulk.
type BinderCreateBulk struct {
	config
	err      error
	builders []*BinderCreate
}

// Save creates the Binder entities in the database.
func (bcb *BinderCreateBulk) Save(ctx context.Context) ([]*Binder, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Binder, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BinderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BinderCreateBulk) SaveX(ctx context.Context) []*Binder {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BinderCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BinderCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
