// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Action is the predicate function for action builders.
type Action func(*sql.Selector)

// Appconf is the predicate function for appconf builders.
type Appconf func(*sql.Selector)

// Binder is the predicate function for binder builders.
type Binder func(*sql.Selector)

// Note is the predicate function for note builders.
type Note func(*sql.Selector)
