// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/enuesaa/pinit/pkg/ent/appconf"
)

// AppconfCreate is the builder for creating a Appconf entity.
type AppconfCreate struct {
	config
	mutation *AppconfMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (ac *AppconfCreate) SetKey(s string) *AppconfCreate {
	ac.mutation.SetKey(s)
	return ac
}

// SetValue sets the "value" field.
func (ac *AppconfCreate) SetValue(s string) *AppconfCreate {
	ac.mutation.SetValue(s)
	return ac
}

// SetCreatedAt sets the "created_at" field.
func (ac *AppconfCreate) SetCreatedAt(t time.Time) *AppconfCreate {
	ac.mutation.SetCreatedAt(t)
	return ac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ac *AppconfCreate) SetNillableCreatedAt(t *time.Time) *AppconfCreate {
	if t != nil {
		ac.SetCreatedAt(*t)
	}
	return ac
}

// SetUpdatedAt sets the "updated_at" field.
func (ac *AppconfCreate) SetUpdatedAt(t time.Time) *AppconfCreate {
	ac.mutation.SetUpdatedAt(t)
	return ac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ac *AppconfCreate) SetNillableUpdatedAt(t *time.Time) *AppconfCreate {
	if t != nil {
		ac.SetUpdatedAt(*t)
	}
	return ac
}

// SetID sets the "id" field.
func (ac *AppconfCreate) SetID(u uint) *AppconfCreate {
	ac.mutation.SetID(u)
	return ac
}

// Mutation returns the AppconfMutation object of the builder.
func (ac *AppconfCreate) Mutation() *AppconfMutation {
	return ac.mutation
}

// Save creates the Appconf in the database.
func (ac *AppconfCreate) Save(ctx context.Context) (*Appconf, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AppconfCreate) SaveX(ctx context.Context) *Appconf {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AppconfCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AppconfCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AppconfCreate) defaults() {
	if _, ok := ac.mutation.CreatedAt(); !ok {
		v := appconf.DefaultCreatedAt()
		ac.mutation.SetCreatedAt(v)
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		v := appconf.DefaultUpdatedAt()
		ac.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AppconfCreate) check() error {
	if _, ok := ac.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "Appconf.key"`)}
	}
	if _, ok := ac.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "Appconf.value"`)}
	}
	if _, ok := ac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Appconf.created_at"`)}
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Appconf.updated_at"`)}
	}
	return nil
}

func (ac *AppconfCreate) sqlSave(ctx context.Context) (*Appconf, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AppconfCreate) createSpec() (*Appconf, *sqlgraph.CreateSpec) {
	var (
		_node = &Appconf{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(appconf.Table, sqlgraph.NewFieldSpec(appconf.FieldID, field.TypeUint))
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.Key(); ok {
		_spec.SetField(appconf.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := ac.mutation.Value(); ok {
		_spec.SetField(appconf.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := ac.mutation.CreatedAt(); ok {
		_spec.SetField(appconf.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ac.mutation.UpdatedAt(); ok {
		_spec.SetField(appconf.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AppconfCreateBulk is the builder for creating many Appconf entities in bulk.
type AppconfCreateBulk struct {
	config
	err      error
	builders []*AppconfCreate
}

// Save creates the Appconf entities in the database.
func (acb *AppconfCreateBulk) Save(ctx context.Context) ([]*Appconf, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Appconf, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppconfMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AppconfCreateBulk) SaveX(ctx context.Context) []*Appconf {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AppconfCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AppconfCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
